"""
Audio device detection for ALSA-only architecture.

Prioritizes ReSpeaker 4 Mic Array with hardware AEC.
Falls back to best available mic/speaker if ReSpeaker not found.
"""

import os
import shutil
import subprocess
from datetime import datetime
import sounddevice as sd
from lib.config import Config


def generate_asound_conf(card_number: int) -> str:
    """
    Generate ALSA configuration for ReSpeaker with software volume control.
    
    Args:
        card_number: ALSA card number for ReSpeaker (e.g., 2, 3, etc.)
        
    Returns:
        str: Complete /etc/asound.conf configuration
    """
    return f"""# =============================================================================
# ALSA Configuration - ReSpeaker with Software Volume
# Auto-generated by raspberry-pi-client for card {card_number}
# =============================================================================

# Capture ONLY channel 0 (AEC-processed audio)
pcm.respeaker_aec {{
    type route
    slave {{
        pcm "hw:{card_number},0"
        channels 6
    }}
    ttable.0.0 1
}}

pcm.respeaker_mono {{
    type plug
    slave.pcm "respeaker_aec"
}}

# Playback to ReSpeaker with software volume control
pcm.respeaker_out_raw {{
    type plug
    slave.pcm "hw:{card_number},0"
}}

pcm.respeaker_out {{
    type softvol
    slave.pcm "respeaker_out_raw"
    control {{
        name "Softvol"
        card {card_number}
    }}
    min_dB -30.0
    max_dB 0.0
}}

# Default: asymmetric (different for playback/capture)
pcm.!default {{
    type asym
    playback.pcm "respeaker_out"
    capture.pcm "respeaker_mono"
}}

ctl.!default {{
    type hw
    card {card_number}
}}
"""


def get_alsa_card_number(device_name: str) -> int:
    """
    Get ALSA card number from device name.
    
    Args:
        device_name: Device name from sounddevice (e.g., "ReSpeaker 4 Mic Array (UAC1.0)")
        
    Returns:
        int: ALSA card number, or None if not found
    """
    try:
        # Use aplay -l to get ALSA card numbers
        result = subprocess.run(
            ["aplay", "-l"],
            capture_output=True,
            text=True,
            timeout=5
        )
        
        if result.returncode != 0:
            return None
        
        # Parse output to find card number
        # Format: "card 2: ArrayUAC10 [ReSpeaker 4 Mic Array (UAC1.0)], device 0: USB Audio [USB Audio]"
        for line in result.stdout.split('\n'):
            if 'card' in line.lower():
                # Check if this line contains our device name (or part of it)
                # ReSpeaker may appear as "ReSpeaker", "ArrayUAC10", "UAC1.0", etc.
                if any(keyword.lower() in line.lower() for keyword in ['respeaker', 'arrayuac10', 'uac1.0']):
                    # Extract card number: "card 2: ..."
                    import re
                    match = re.search(r'card\s+(\d+):', line)
                    if match:
                        card_num = int(match.group(1))
                        return card_num
        
        return None
        
    except Exception as e:
        print(f"  ⚠ Could not determine ALSA card number: {e}")
        return None


def set_softvol(volume_percent: int, card: int) -> bool:
    """
    Set the ALSA softvol control volume using amixer.
    
    Note: Softvol control is created when the PCM device is first opened.
    If the control doesn't exist yet, this will attempt to initialize it.
    
    Args:
        volume_percent: Volume level (0-100)
        card: ALSA card number (detected dynamically)
        
    Returns:
        bool: True if volume set successfully, False otherwise
    """
    logger = Config.LOGGER
    
    try:
        # Clamp volume to valid range
        volume_percent = max(0, min(100, volume_percent))
        
        print(f"  Setting softvol to {volume_percent}%...")
        
        # First check if Softvol control exists
        # amixer -c <card> sget Softvol
        check_result = subprocess.run(
            ["amixer", "-c", str(card), "sget", "Softvol"],
            capture_output=True,
            text=True,
            timeout=5
        )
        
        if check_result.returncode != 0:
            # Softvol doesn't exist yet - need to initialize it
            # This happens when /etc/asound.conf was just created
            # Try to trigger initialization by briefly opening the default device
            print(f"  Softvol control not found, initializing...")
            try:
                # Query default device to trigger ALSA initialization
                import sounddevice as sd
                # Just query the device, don't actually open a stream
                devices = sd.query_devices()
                default_device = sd.query_devices(kind='output')
            except Exception as init_error:
                print(f"  ⚠ Could not initialize softvol: {init_error}")
            
            # Try again after initialization attempt
            check_result = subprocess.run(
                ["amixer", "-c", str(card), "sget", "Softvol"],
                capture_output=True,
                text=True,
                timeout=5
            )
            
            if check_result.returncode != 0:
                print(f"  ⚠ Softvol control still not available (may initialize on first audio playback)")
                if logger:
                    logger.warning(
                        "softvol_not_available",
                        extra={
                            "volume_percent": volume_percent,
                            "card": card,
                            "user_id": Config.USER_ID
                        }
                    )
                return False
        
        # Set volume using amixer: amixer -c <card> set Softvol <volume>%
        result = subprocess.run(
            ["amixer", "-c", str(card), "set", "Softvol", f"{volume_percent}%"],
            capture_output=True,
            text=True,
            timeout=5
        )
        
        if result.returncode != 0:
            print(f"  ⚠ Failed to set softvol: {result.stderr.strip()}")
            if logger:
                logger.warning(
                    "softvol_set_failed",
                    extra={
                        "volume_percent": volume_percent,
                        "card": card,
                        "error": result.stderr.strip(),
                        "user_id": Config.USER_ID
                    }
                )
            return False
        
        print(f"  ✓ Softvol set to {volume_percent}%")
        if logger:
            logger.info(
                "softvol_set",
                extra={
                    "volume_percent": volume_percent,
                    "card": card,
                    "user_id": Config.USER_ID
                }
            )
        return True
        
    except subprocess.TimeoutExpired:
        print(f"  ⚠ Timeout setting softvol")
        if logger:
            logger.error(
                "softvol_timeout",
                extra={
                    "volume_percent": volume_percent,
                    "card": card,
                    "user_id": Config.USER_ID
                }
            )
        return False
    except FileNotFoundError:
        print(f"  ⚠ amixer command not found (install alsa-utils)")
        return False
    except Exception as e:
        print(f"  ⚠ Error setting softvol: {e}")
        if logger:
            logger.error(
                "softvol_error",
                extra={
                    "volume_percent": volume_percent,
                    "card": card,
                    "error": str(e),
                    "user_id": Config.USER_ID
                },
                exc_info=True
            )
        return False


def ensure_alsa_config(card_number: int):
    """
    Ensure /etc/asound.conf is properly configured for ReSpeaker with softvol.
    
    This function:
    1. Checks if /etc/asound.conf exists
    2. Verifies it contains softvol configuration for the correct card
    3. If missing or incorrect card, creates/updates it (with backup)
    4. Is idempotent (safe to run multiple times)
    
    Args:
        card_number: ALSA card number for ReSpeaker (detected dynamically)
    
    Returns:
        bool: True if config is correct, False if there was an error
    """
    logger = Config.LOGGER
    asound_conf_path = '/etc/asound.conf'
    
    try:
        # Check if file exists
        if os.path.exists(asound_conf_path):
            # Read existing config
            with open(asound_conf_path, 'r') as f:
                existing_config = f.read()
            
            # Check if it has the required components
            has_softvol = 'softvol' in existing_config.lower()
            has_respeaker_aec = 'respeaker_aec' in existing_config.lower()
            has_default_pcm = 'pcm.!default' in existing_config
            
            # Check if it's configured for the correct card number
            # Look for patterns like "hw:2,0" or "card 2"
            has_correct_card = f"hw:{card_number}," in existing_config or f"card {card_number}" in existing_config
            
            if has_softvol and has_respeaker_aec and has_default_pcm and has_correct_card:
                # Config looks good
                print(f"✓ /etc/asound.conf: Already configured for card {card_number} with softvol")
                if logger:
                    logger.info(
                        "alsa_config_verified",
                        extra={
                            "config_path": asound_conf_path,
                            "status": "valid",
                            "card_number": card_number,
                            "user_id": Config.USER_ID
                        }
                    )
                return True
            else:
                # Config exists but is incomplete or wrong card
                if not has_correct_card and has_softvol:
                    print(f"⚠ /etc/asound.conf: Configured for wrong card, updating to card {card_number}...")
                else:
                    print(f"⚠ /etc/asound.conf: Existing but missing softvol/AEC config")
                print("  Creating backup and updating...")
                
                # Backup existing config using sudo
                timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
                backup_path = f"{asound_conf_path}.backup.{timestamp}"
                try:
                    subprocess.run(
                        ["sudo", "cp", asound_conf_path, backup_path],
                        capture_output=True,
                        timeout=5,
                        check=True
                    )
                    print(f"  ✓ Backed up to: {backup_path}")
                except subprocess.CalledProcessError as e:
                    print(f"  ⚠ Could not backup config: {e}")
                except Exception as e:
                    print(f"  ⚠ Backup error: {e}")
                
                if logger:
                    logger.info(
                        "alsa_config_backup_created",
                        extra={
                            "config_path": asound_conf_path,
                            "backup_path": backup_path,
                            "reason": "incomplete_or_wrong_card",
                            "card_number": card_number,
                            "user_id": Config.USER_ID
                        }
                    )
        else:
            # Config doesn't exist
            print(f"⚠ /etc/asound.conf: Not found, creating for card {card_number} with softvol...")
            
            if logger:
                logger.info(
                    "alsa_config_missing",
                    extra={
                        "config_path": asound_conf_path,
                        "action": "creating",
                        "card_number": card_number,
                        "user_id": Config.USER_ID
                    }
                )
        
        # Write the configuration with correct card number
        # Use sudo since /etc/asound.conf requires root permissions
        asound_config = generate_asound_conf(card_number)
        
        # Write config using sudo (service may not run as root)
        try:
            result = subprocess.run(
                ["sudo", "tee", asound_conf_path],
                input=asound_config,
                text=True,
                capture_output=True,
                timeout=5
            )
            
            if result.returncode != 0:
                print(f"✗ Failed to write config: {result.stderr}")
                if logger:
                    logger.error(
                        "alsa_config_write_failed",
                        extra={
                            "config_path": asound_conf_path,
                            "error": result.stderr,
                            "user_id": Config.USER_ID
                        }
                    )
                return False
        except Exception as e:
            print(f"✗ Error writing config: {e}")
            if logger:
                logger.error(
                    "alsa_config_write_error",
                    extra={
                        "config_path": asound_conf_path,
                        "error": str(e),
                        "user_id": Config.USER_ID
                    }
                )
            return False
        
        print(f"✓ /etc/asound.conf: Created for card {card_number} with softvol control")
        print("  ReSpeaker audio routing: Ch0 (AEC) for input, softvol for output")
        
        if logger:
            logger.info(
                "alsa_config_created",
                extra={
                    "config_path": asound_conf_path,
                    "has_softvol": True,
                    "card_number": card_number,
                    "user_id": Config.USER_ID
                }
            )
        
        return True
        
    except PermissionError:
        print(f"✗ /etc/asound.conf: Permission denied (sudo access required)")
        if logger:
            logger.error(
                "alsa_config_permission_denied",
                extra={
                    "config_path": asound_conf_path,
                    "error": "permission_denied",
                    "note": "User must have sudo privileges",
                    "user_id": Config.USER_ID
                }
            )
        return False
        
    except Exception as e:
        print(f"✗ /etc/asound.conf: Error configuring: {e}")
        if logger:
            logger.error(
                "alsa_config_error",
                extra={
                    "config_path": asound_conf_path,
                    "error": str(e),
                    "user_id": Config.USER_ID
                },
                exc_info=True
            )
        return False


def get_audio_devices():
    """
    Detect and return audio device indices for input and output.
    
    Strategy:
    1. Detect ReSpeaker 4 Mic Array
    2. Use ALSA default device (None, None) to route through /etc/asound.conf
    3. ALSA config extracts Channel 0 (AEC-processed audio) from ReSpeaker
    
    Returns:
        tuple: (mic_device_index, speaker_device_index, has_hardware_aec)
               Returns (None, None, True) when ReSpeaker found (uses ALSA Ch0 routing)
               Returns (None, None, False) if ReSpeaker not found (fallback)
    """
    import os
    
    logger = Config.LOGGER
    
    devices = sd.query_devices()
    respeaker_found = False
    respeaker_info = None
    
    # Search for ReSpeaker device
    for idx, dev in enumerate(devices):
        # Check if this is the ReSpeaker device
        if any(keyword in dev['name'].lower() 
               for keyword in ['respeaker', 'arrayuac10', 'uac1.0']):
            # Note: We check for output channels (speaker) - input channels may show 0
            # if device is busy or sounddevice can't query it properly
            if dev['max_output_channels'] > 0:
                respeaker_found = True
                respeaker_info = {
                    'index': idx,
                    'name': dev['name'],
                    'input_channels': dev['max_input_channels'],
                    'output_channels': dev['max_output_channels']
                }
                break
    
    if respeaker_found:
        # Get the ALSA card number for this ReSpeaker device
        # (sounddevice index may not match ALSA card number)
        alsa_card_number = get_alsa_card_number(respeaker_info['name'])
        
        if alsa_card_number is None:
            # Fallback: try using sounddevice index as card number
            print(f"  ⚠ Could not detect ALSA card number, using sounddevice index {respeaker_info['index']}")
            alsa_card_number = respeaker_info['index']
        
        # Ensure ALSA config is properly set up with softvol
        # This auto-creates/updates /etc/asound.conf if needed
        config_created = ensure_alsa_config(alsa_card_number)
        
        print(f"✓ ReSpeaker detected: {respeaker_info['name']}")
        print(f"  Sounddevice index: {respeaker_info['index']}, ALSA card: {alsa_card_number}")
        print(f"  Hardware echo cancellation: Available")
        print(f"  ReSpeaker channels: {respeaker_info['input_channels']} in, {respeaker_info['output_channels']} out")
        print(f"  Audio routing: ALSA default device → /etc/asound.conf")
        print(f"  ✓ Using Channel 0 (AEC-processed audio) from ReSpeaker")
        print(f"  ✓ Software volume control (softvol) enabled")
        
        # Set initial volume from config
        # Note: This happens after ALSA config is created
        volume_percent = Config.SPEAKER_VOLUME_PERCENT
        set_softvol(volume_percent, card=alsa_card_number)
        
        print(f"  Playback: ReSpeaker 3.5mm jack (for AEC reference signal)")
        
        if logger:
            logger.info(
                "respeaker_detected_alsa_routing",
                extra={
                    "device_name": respeaker_info['name'],
                    "sounddevice_index": respeaker_info['index'],
                    "alsa_card_number": alsa_card_number,
                    "input_channels": respeaker_info['input_channels'],
                    "output_channels": respeaker_info['output_channels'],
                    "alsa_config_auto_configured": True,
                    "has_softvol": True,
                    "using_ch0": True,
                    "hardware_aec": True,
                    "routing": "alsa_default",
                    "speaker_volume_percent": Config.SPEAKER_VOLUME_PERCENT,
                    "user_id": Config.USER_ID
                }
            )
        
        # Return None for both - use ALSA default which routes through /etc/asound.conf
        # This ensures we get Ch0 (AEC-processed) instead of raw hardware channels
        return None, None, True
    
    # ReSpeaker not found - fall back to system default
    print("⚠ ReSpeaker not detected - using system default audio")
    print("  Hardware echo cancellation: NOT available")
    print("  Note: Barge-in may not work properly without AEC")
    print("  System will auto-select audio devices via ALSA/PulseAudio")
    print("  Channel routing: Not using ReSpeaker Ch0 (device not found)")
    
    if logger:
        logger.warning(
            "fallback_audio_devices",
            extra={
                "respeaker_found": False,
                "hardware_aec": False,
                "using_system_default": True,
                "using_ch0": False,
                "user_id": Config.USER_ID
            }
        )
    
    # Return None for both - let sounddevice/ALSA/PulseAudio choose the best device
    return None, None, False


def verify_audio_setup():
    """
    Verify ALSA audio setup and log available devices.
    
    This function verifies device detection and logs information for debugging.
    Actual device selection is handled by get_audio_devices().
    """
    print("\n🔊 Verifying ALSA audio setup...")
    print("  Audio Architecture:")
    print("    • ALSA-only (PipeWire/PulseAudio disabled)")
    print("    • Priority: ReSpeaker 4 Mic Array v2.0")
    print("    • Fallback: Best available mic/speaker")
    
    try:
        # Query available audio devices via sounddevice
        devices = sd.query_devices()
        print("\n  Available ALSA devices:")
        
        for idx, dev in enumerate(devices):
            # Check if this is the ReSpeaker
            is_respeaker = any(keyword in dev['name'].lower() 
                             for keyword in ['respeaker', 'arrayuac10', 'uac1.0'])
            
            if is_respeaker:
                print(f"    ✓ [{idx}] {dev['name']} (ReSpeaker - hardware AEC)")
                print(f"        Input channels: {dev['max_input_channels']}")
                print(f"        Output channels: {dev['max_output_channels']}")
            else:
                # Log other devices for debugging
                in_ch = dev['max_input_channels']
                out_ch = dev['max_output_channels']
                caps = []
                if in_ch > 0:
                    caps.append(f"in:{in_ch}")
                if out_ch > 0:
                    caps.append(f"out:{out_ch}")
                cap_str = f" ({', '.join(caps)})" if caps else ""
                print(f"      [{idx}] {dev['name']}{cap_str}")
        
        print()  # Blank line for readability
            
    except Exception as e:
        print(f"  ⚠ Could not query audio devices: {e}")
        print("    This may indicate ALSA configuration issues")
        
        logger = Config.LOGGER
        if logger:
            logger.error(
                "audio_device_query_failed",
                extra={
                    "error": str(e),
                    "user_id": Config.USER_ID
                },
                exc_info=True
            )

